### ISSUE TITLE
Non-Verified

### ISSUE THREAD

**Issue by NEVARC76** [Eryux/dummybot-discord#1]
The bot cant join anymore servers because it isn't verified

**Comment by ChobobDev** [comment]
I am facing this problem as well.

**Comment by Eryux** [comment]
Hello, sorry for this silence, I was quite busy working on other things.

I know about the bot can't join more servers because of its unverified status. In fact, I launch the verification procedure months ago. Discord team answer me nearly two month after and asked me to detail more about what the bot do and what data it uses. I tried to do that but explaining that the goal of the bot is to not do nothing isn't really easy to understand for Discord support apparently, since I've no news.

Anyway, I shuted down the bot early september or something like that waiting for the verified status. But like it may will never come, I decided to shutdown the bot indefinately.

At its start the bot was made for testing, it also offer a base for people who want to try python discord bot development so I will try to maintain bot code if people want to launch their version of the bot
